[App]
Name = "ai.h2o.wave.ask_h2o"
Version = "0.0.4"
Title = "Ask H2O"
Description = "Conversationally explore H2O.ai’s website, products, and more"
Tags = ["GENERATIVE_AI", "DEMO", "INTERNAL", "DATA_SCIENCE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "src.app"
EnableOIDC = false
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"


[[Env]]
Name = "H2OGPTE_API_TOKEN"
Secret = "ask-h2o"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "ask-h2o"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
