[App]
Name = "ai.h2o.wave.bingo_new_years_cards"
Version = "0.0.21"
Title = "Bingo Goals"
Description = "Use AI to generate your Bingo Goals card"
Tags = ["GENERATIVE_AI", "DATA_SCIENCE", "OSS", "AI_FOR_LIFE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "app"
EnableOIDC = true
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpte-shared"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
