[App]
Name = "ai.h2o.wave.bingo_new_years_cards"
Version = "1.0.0"
Title = "Holiday Bingo"
Description = "Use AI to generate your 2024 goals bingo card!"
Tags = ["GENERATIVE_AI", "OSS", "AI_FOR_LIFE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
RuntimeVersion="deb11_py310_wlatest"
Module = "app"
EnableOIDC = true
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpte-genai"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"