COMPANY = 'H2O'
APP_TITLE = 'H2OGPT'
LOADING_GIF = './static/loader_legal.gif'
COMPANY_LOGO = "./static/icon.png"
H2O_LOGO = 'static/h2o_logo.png'
COMPANY_SEC_IMAGE = "./static/h2ogpte_logo.png"
VLINE = './static/vline.png'
PROCESSOS_FOLDER = './processos_iniciais_v2'
TEMP_NEW_PROCESS_FOLDER = './temp_new_process_'
TEMP_FOLDER_ZIPFILES = './temp_folder_zip_files'
LOGO_DIM = (500,500)
H2O_LOGO_DIM = (225,225)
SEC_IMAGE_DIM = (360,150)
FACTOR_LOGO = 0.15
FACTOR_SEC_IMAGE = 0.35
FACTOR_H2O_LOGO = 0.3
LLM = "h2oai/h2ogpt-4096-llama2-70b-chat-4bit"
# LLM = "HuggingFaceH4/zephyr-7b-beta"
# LLM = "h2oai/h2ogpt-gm-7b-mistral-chat-sft-dpo-v1"